title: "Mohammad Taslimi"
author: "Mohammad Taslimi"
description: "Sharif University of Technology"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {title: "CV", url: "/assets/CV.pdf", icon: "file-pdf", download: true}
  - {file: "courses.md", title: Favorite Courses}
  - {file: "projects.md", title: Projects}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "javascript:copyToClipboard('mohammadtaslimi.sut@gmail.com')"}
  - {title: Github, icon: github, url: "https://github.com/MoTa2380/"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/mohammad-taslimi-ab4755239/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
